name: deploy to dev

on:
    push:
        branches:
            - develop
env:
    PORT: 5000

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3.1.0
            - name: build docker image
              run: |
                  export DOCKER_BUILDKIT=1
                  docker build --no-cache -t test\
                  --build-arg PORT=${{ env.PORT }} .
                  docker push test
